import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { useNavigate } from "react-router-dom";
import {
  BadgeDollarSign, Building2, CreditCard, MoreHorizontal, Plus,
  Printer, ReceiptText, Search, Truck, WalletCards,
} from "lucide-react";
import { useJsonCollection } from "../hooks/useJsonCollection";
import { confirmAction } from "../utils/confirmDialog";
import { notify } from "../utils/notify";
import "./Payables.css";

const languageKey="afghan-power-language";
const numeric=(value)=>Number(value||0)||0;
const translations={
 en:{title:"Payables",subtitle:"Suppliers with unpaid purchase balances are listed here.",batchPay:"Pay Payables",search:"Search supplier, phone or currency...",suppliersDue:"Suppliers Due",totalPurchases:"Total Purchases",totalPaid:"Total Paid",outstanding:"Outstanding",supplier:"Supplier",phone:"Phone",purchases:"Purchases",purchased:"Purchased",paid:"Paid",balance:"Balance Due",currency:"Currency",actions:"Actions",menu:"Actions",pay:"Payment",makePaid:"Make as Paid",print:"Print",bill:"Bill",paidSuccess:"Supplier balance marked as paid.",makePaidTitle:"Mark supplier balance as paid?",makePaidMessage:"This will record a payment for the full outstanding balance.",confirm:"Confirm",cancel:"Cancel",noData:"No unpaid supplier balances were found.",settled:"All supplier accounts are currently settled."},
 fa:{title:"تادیات",subtitle:"تأمین‌کننده‌هایی که پول خریداری‌های شان هنوز مکمل پرداخت نشده در اینجا نمایش داده می‌شوند.",batchPay:"پرداخت تادیات",search:"جستجوی تأمین‌کننده، شماره تماس یا ارز...",suppliersDue:"تأمین‌کننده بدهکار",totalPurchases:"مجموع خریداری",totalPaid:"مجموع پرداخت",outstanding:"مجموع باقی‌مانده",supplier:"تأمین‌کننده",phone:"شماره تماس",purchases:"تعداد خریداری",purchased:"مجموع خرید",paid:"پرداخت‌شده",balance:"باقی / قابل پرداخت",currency:"واحد پول",actions:"عملیات",menu:"عملیات",pay:"پرداخت",makePaid:"پرداخت مکمل",print:"چاپ",bill:"بل",paidSuccess:"حساب تأمین‌کننده مکمل پرداخت شد.",makePaidTitle:"حساب تأمین‌کننده مکمل پرداخت شود؟",makePaidMessage:"به اندازه تمام باقی‌مانده یک پرداخت جدید ثبت می‌شود.",confirm:"تأیید",cancel:"لغو",noData:"هیچ حساب پرداخت‌نشده‌ای برای تأمین‌کننده‌ها وجود ندارد.",settled:"فعلاً حساب تمام تأمین‌کننده‌ها تصفیه است."},
 ps:{title:"تادیات",subtitle:"هغه عرضه کوونکي چې د پېرود پیسې یې لا بشپړې نه دي ورکړل شوې دلته ښودل کېږي.",batchPay:"د تادیاتو ورکړه",search:"عرضه کوونکی، د اړیکې شمېره یا اسعار ولټوئ...",suppliersDue:"پاتې عرضه کوونکي",totalPurchases:"ټول پېرود",totalPaid:"ټولې ورکړې",outstanding:"ټولې پاتې پیسې",supplier:"عرضه کوونکی",phone:"د اړیکې شمېره",purchases:"د پېرود شمېر",purchased:"د پېرود مجموعه",paid:"ورکړل شوي",balance:"پاتې / ورکول کېدونکي",currency:"اسعار",actions:"عملیات",menu:"عملیات",pay:"تادیه",makePaid:"بشپړ تادیه",print:"چاپ",bill:"بل",paidSuccess:"د عرضه کوونکي حساب بشپړ تادیه شو.",makePaidTitle:"د عرضه کوونکي حساب بشپړ تادیه شي؟",makePaidMessage:"د ټول پاتې مبلغ په اندازه نوې تادیه ثبتېږي.",confirm:"تایید",cancel:"لغوه",noData:"د عرضه کوونکو لپاره هېڅ پاتې حساب نشته.",settled:"اوس مهال د ټولو عرضه کوونکو حسابونه تصفیه دي."}
};
function currencyCode(supplier){const raw=String(supplier?.currency||supplier?.currencyCode||"AFN").toUpperCase();if(raw.includes("USD"))return"USD";if(raw.includes("EUR"))return"EUR";if(raw.includes("INR"))return"INR";return"AFN"}
export default function Payables(){
 const navigate=useNavigate();
 const [suppliers]=useJsonCollection("suppliers");const [purchases]=useJsonCollection("purchases");const [purchaseReturns]=useJsonCollection("purchaseReturns");const [supplierPayments,setSupplierPayments]=useJsonCollection("supplierPayments");
 const [language,setLanguage]=useState(()=>localStorage.getItem(languageKey)||"fa");const [search,setSearch]=useState("");const [actionMenu,setActionMenu]=useState(null);const t=translations[language]||translations.fa;
 useEffect(()=>{const f=()=>setLanguage(localStorage.getItem(languageKey)||"fa");window.addEventListener("storage",f);window.addEventListener("app-language-updated",f);return()=>{window.removeEventListener("storage",f);window.removeEventListener("app-language-updated",f)}},[]);
 useEffect(()=>{if(!actionMenu)return;const close=()=>setActionMenu(null);window.addEventListener("resize",close);window.addEventListener("scroll",close,true);return()=>{window.removeEventListener("resize",close);window.removeEventListener("scroll",close,true)}},[actionMenu]);
 const rows=useMemo(()=>suppliers.map(supplier=>{const id=String(supplier.id);const sp=purchases.filter(x=>String(x.supplierId)===id);const sr=purchaseReturns.filter(x=>String(x.supplierId)===id);const mp=supplierPayments.filter(x=>String(x.supplierId)===id);const totalPurchased=sp.reduce((s,x)=>s+numeric(x.totalAmount),0);const paidAtPurchase=sp.reduce((s,x)=>s+numeric(x.paidAmount),0);const paidLater=mp.reduce((s,x)=>s+numeric(x.amount),0);const returned=sr.reduce((s,x)=>s+numeric(x.totalAmount),0);const opening=numeric(supplier.openingBalance);const totalPaid=paidAtPurchase+paidLater+returned+Math.max(-opening,0);const balance=Math.max(totalPurchased+Math.max(opening,0)-paidAtPurchase-paidLater-returned,0);const unpaid=sp.map(p=>({...p,calculatedRemaining:Math.max(numeric(p.remainingAmount??(numeric(p.totalAmount)-numeric(p.paidAmount))),0)})).filter(p=>p.calculatedRemaining>.0001).sort((a,b)=>new Date(a.purchaseDate||a.createdAt||0)-new Date(b.purchaseDate||b.createdAt||0));return{supplier,purchaseCount:sp.length,totalPurchased,totalPaid,balance,currency:currencyCode(supplier),focusPurchase:unpaid[0]||sp[sp.length-1]||null}}).filter(x=>x.balance>.0001).sort((a,b)=>b.balance-a.balance),[suppliers,purchases,purchaseReturns,supplierPayments]);
 const filteredRows=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(({supplier,currency})=>[supplier.name,supplier.supplierName,supplier.contactPerson,supplier.phone,supplier.phoneNumber,currency].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[rows,search]);
 const totalsByCurrency=useMemo(()=>{const r={};rows.forEach(row=>{if(!r[row.currency])r[row.currency]={purchased:0,paid:0,balance:0};r[row.currency].purchased+=row.totalPurchased;r[row.currency].paid+=row.totalPaid;r[row.currency].balance+=row.balance});return r},[rows]);
 const totalText=(field)=>Object.entries(totalsByCurrency).filter(([,v])=>v[field]>0).map(([c,v])=>`${c} ${v[field].toLocaleString(undefined,{maximumFractionDigits:2})}`).join(" · ")||"—";
 const openSupplierLedger=(row,openPayment=false)=>{const purchaseId=row.focusPurchase?.id||"";navigate(`/supplier-detail/${row.supplier.id}?highlightPurchase=${encodeURIComponent(purchaseId)}`,{state:{openPayment,highlightPurchaseId:purchaseId}})};
 const openMenu=(event,payload)=>{event.stopPropagation();const rect=event.currentTarget.getBoundingClientRect();const width=148,height=156,gap=5;const below=window.innerHeight-rect.bottom>height+12;const top=below?rect.bottom+gap:Math.max(8,rect.top-height-gap);let left=(document.documentElement.dir==="rtl"||language!=="en")?rect.right-width:rect.left;left=Math.min(Math.max(8,left),window.innerWidth-width-8);setActionMenu({payload,top,left})};
 const makeAsPaid=async(row)=>{const ok=await confirmAction({title:t.makePaidTitle,message:t.makePaidMessage,confirmText:t.confirm,cancelText:t.cancel});if(!ok)return;const now=new Date();const record={id:`SPAY-${Date.now()}`,supplierId:row.supplier.id,supplierName:row.supplier.name||row.supplier.supplierName||"",date:now.toISOString().slice(0,10),amount:row.balance,currency:row.currency,description:t.makePaid,reference:`PAY-${String(Date.now()).slice(-7)}`,createdAt:now.toISOString()};if(await setSupplierPayments([record,...supplierPayments]))notify(t.paidSuccess,"success")};
 return <section className="payables-page">
  <div className="payables-header"><div><div className="payables-title-line"><BadgeDollarSign size={24}/><h1>{t.title}</h1></div><p>{t.subtitle}</p></div><button className="payables-batch-btn" onClick={()=>navigate("/payables/payments/new")}><Plus size={15}/>{t.batchPay}</button></div>
  <div className="payables-stats"><article className="payables-stat-card"><div className="payables-stat-icon"><Truck size={19}/></div><span>{t.suppliersDue}</span><strong>{rows.length}</strong></article><article className="payables-stat-card"><div className="payables-stat-icon"><Building2 size={19}/></div><span>{t.totalPurchases}</span><strong>{totalText("purchased")}</strong></article><article className="payables-stat-card"><div className="payables-stat-icon"><CreditCard size={19}/></div><span>{t.totalPaid}</span><strong>{totalText("paid")}</strong></article><article className="payables-stat-card is-due"><div className="payables-stat-icon"><WalletCards size={19}/></div><span>{t.outstanding}</span><strong>{totalText("balance")}</strong></article></div>
  <div className="payables-card"><div className="payables-toolbar"><label className="payables-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/></label></div><div className="payables-table-wrap"><table className="payables-table"><thead><tr><th>{t.supplier}</th><th>{t.phone}</th><th>{t.purchases}</th><th>{t.purchased}</th><th>{t.paid}</th><th>{t.balance}</th><th>{t.currency}</th><th>{t.actions}</th></tr></thead><tbody>{filteredRows.map(row=>{const {supplier,purchaseCount,totalPurchased,totalPaid,balance,currency}=row;const name=supplier.name||supplier.supplierName||"—";return <tr key={supplier.id} className="payables-clickable-row" onClick={()=>openSupplierLedger(row)}><td><div className="payables-supplier-cell"><span className="payables-supplier-icon"><Truck size={15}/></span><div><strong>{name}</strong><small>{supplier.contactPerson||""}</small></div></div></td><td>{supplier.phone||supplier.phoneNumber||"—"}</td><td>{purchaseCount}</td><td>{totalPurchased.toLocaleString()}</td><td>{totalPaid.toLocaleString()}</td><td><span className="payables-balance-pill">{balance.toLocaleString()}</span></td><td><span className="payables-currency-pill">{currency}</span></td><td className="payables-actions-cell" onClick={e=>e.stopPropagation()}><button className="payables-action-trigger" onClick={e=>openMenu(e,row)}><MoreHorizontal size={16}/></button></td></tr>})}{!filteredRows.length&&<tr><td colSpan="8" className="payables-empty"><WalletCards size={30}/><strong>{t.noData}</strong><span>{t.settled}</span></td></tr>}</tbody></table></div></div>
  {actionMenu&&createPortal(<div className="payables-action-popover" style={{top:actionMenu.top,left:actionMenu.left}}><button onClick={()=>{const r=actionMenu.payload;setActionMenu(null);openSupplierLedger(r,true)}}><CreditCard size={14}/><span>{t.pay}</span></button><button onClick={()=>{const r=actionMenu.payload;setActionMenu(null);makeAsPaid(r)}}><WalletCards size={14}/><span>{t.makePaid}</span></button><button disabled={!actionMenu.payload.focusPurchase} onClick={()=>{const p=actionMenu.payload.focusPurchase;setActionMenu(null);if(p)navigate(`/purchasing/${p.id}/print`)}}><Printer size={14}/><span>{t.print}</span></button><button disabled={!actionMenu.payload.focusPurchase} onClick={()=>{const p=actionMenu.payload.focusPurchase;setActionMenu(null);if(p)navigate(`/purchasing/${p.id}`)}}><ReceiptText size={14}/><span>{t.bill}</span></button></div>,document.body)}
 </section>
}
