import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Printer } from "lucide-react";
import { useJsonCollection } from "../hooks/useJsonCollection";
import "./PrintPayablesBatch.css";

const key="afghan-power-language";
const tr={en:{title:"Payables Payment Report",back:"Back",print:"Print",ref:"Reference",date:"Date",supplier:"Supplier",currency:"Currency",amount:"Amount",note:"Note",total:"Total",count:"Suppliers",missing:"Payment batch not found."},fa:{title:"راپور پرداخت تادیات",back:"برگشت",print:"پرنت",ref:"مرجع",date:"تاریخ",supplier:"تأمین‌کننده",currency:"واحد پول",amount:"مبلغ",note:"یادداشت",total:"مجموع",count:"تعداد تأمین‌کننده",missing:"ریکارد پرداخت تادیات پیدا نشد."},ps:{title:"د تادیاتو د ورکړې راپور",back:"بېرته",print:"پرنټ",ref:"مرجع",date:"نېټه",supplier:"عرضه کوونکی",currency:"اسعار",amount:"مبلغ",note:"یادښت",total:"ټول",count:"د عرضه کوونکو شمېر",missing:"د تادیاتو د ورکړې ریکارډ ونه موندل شو."}};
export default function PrintPayablesBatch(){const {batchId}=useParams();const navigate=useNavigate();const [batches]=useJsonCollection("supplierPaymentBatches");const [language,setLanguage]=useState(()=>localStorage.getItem(key)||"fa");useEffect(()=>{const f=()=>setLanguage(localStorage.getItem(key)||"fa");window.addEventListener("app-language-updated",f);return()=>window.removeEventListener("app-language-updated",f)},[]);const t=tr[language]||tr.fa;const dir=language==="en"?"ltr":"rtl";const batch=batches.find(x=>String(x.id)===String(batchId));if(!batch)return <div className="pb-print-missing">{t.missing}</div>;const totals=batch.totals||{};return <div className="pb-print-page" dir={dir}><div className="pb-print-toolbar"><button onClick={()=>navigate("/payables")}><ArrowLeft size={16}/>{t.back}</button><button className="primary" onClick={()=>window.print()}><Printer size={16}/>{t.print}</button></div><article className="pb-print-paper"><header><div className="brand"><strong>APG</strong><span>Pharmacy & Medicine Management System</span></div><div className="heading"><h1>{t.title}</h1><p>{t.ref}: <b>{batch.reference}</b> &nbsp; • &nbsp; {t.date}: <b>{batch.date}</b></p></div></header><div className="pb-print-meta"><div><span>{t.count}</span><b>{batch.payments?.length||0}</b></div>{Object.entries(totals).map(([code,value])=><div key={code}><span>{t.total} {code}</span><b>{Number(value||0).toLocaleString(undefined,{maximumFractionDigits:2})}</b></div>)}</div><table><thead><tr><th>#</th><th>{t.supplier}</th><th>{t.currency}</th><th>{t.amount}</th><th>{t.note}</th></tr></thead><tbody>{(batch.payments||[]).map((row,i)=><tr key={row.paymentId||row.id||i}><td>{i+1}</td><td>{row.supplierName||"—"}</td><td>{row.currency||"AFN"}</td><td>{Number(row.amount||0).toLocaleString(undefined,{maximumFractionDigits:2})}</td><td>{row.note||"—"}</td></tr>)}</tbody></table><footer><span>____________________</span><span>____________________</span></footer></article></div>}
