import { useEffect, useMemo, useState } from "react";
import { Download, FileBarChart, Printer, Save, Search, Settings2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import ShamsiDateInput from "../components/ShamsiDateInput";
import { useJsonCollection } from "../hooks/useJsonCollection";
import { formatAfghanDate, todayDateValue } from "../utils/afghanDate";
import "./Reports.css";

const reportTypes = [["purchases","خریداری"],["sales","فروشات"],["purchaseReturns","برگشت خریداری / نمونه / تاریخ‌گذشته"],["saleReturns","برگشت فروش / موجودی افتتاحیه"],["payables","تادیات"],["receivables","طلبات"],["cashFlow","جریان نقدی"],["expenses","مصارف"],["profit","مفاد"],["dayBook","روزنامچه عمومی"]];
const bases = {
  purchases:[["supplier","تأمین‌کننده"],["product","محصول"],["company","کمپنی"],["country","ساخت کشور"],["group","گروپ"],["batch","لات نمبر"],["supplierProduct","تأمین‌کننده - محصول"],["productSupplier","محصول - تأمین‌کننده"]],
  sales:[["customer","مشتری"],["product","محصول"],["company","کمپنی"],["country","ساخت کشور"],["group","گروپ"],["batch","لات نمبر"],["customerProduct","مشتری - محصول"],["productCustomer","محصول - مشتری"]],
  purchaseReturns:[["supplier","تأمین‌کننده"],["product","محصول"]],saleReturns:[["customer","مشتری"],["product","محصول"]],payables:[["supplier","تأمین‌کننده"]],receivables:[["customer","مشتری"]],cashFlow:[["party","شخص / حساب"]],expenses:[["party","شخص / حساب"]],profit:[["product","محصول"],["customer","مشتری"]],dayBook:[["party","شخص / حساب"],["product","محصول"]],
};
const n=(v)=>Number(v)||0;
const dateOf=(x)=>String(x?.purchaseDate||x?.saleDate||x?.returnDate||x?.date||x?.createdAt||"").slice(0,10);
const money=(v)=>n(v).toLocaleString("en-US",{maximumFractionDigits:2});
const today=()=>todayDateValue?.()||new Date().toISOString().slice(0,10);
const iso=(d)=>d.toISOString().slice(0,10);
const weekStart=(date)=>{const d=new Date(date);d.setDate(d.getDate()-((d.getDay()+1)%7));return d};
function row(source,item,extra={}){return{id:`${source}-${item.id||Math.random()}-${extra.id||""}`,source,date:dateOf(item),reference:item.systemBillNumber||item.invoiceNumber||item.billNumber||item.reference||item.id||"-",party:extra.party||item.supplierName||item.customerName||item.partyName||item.description||"-",supplier:item.supplierName||"",customer:item.customerName||"",product:extra.product||item.productName||"",company:extra.company||"",country:extra.country||"",group:extra.group||"",batch:extra.batch||item.batchNo||"",quantity:n(extra.quantity??item.quantity??item.itemCount),amount:n(extra.amount??item.totalAmount??item.amount),cost:n(extra.cost),currency:item.currency||extra.currency||"AFN",details:extra.details||item.description||"-"}}

export default function Reports(){
  const navigate=useNavigate();
  const [purchases]=useJsonCollection("purchases"),[purchaseItems]=useJsonCollection("purchaseItems"),[sales]=useJsonCollection("salesRegister"),[purchaseReturns]=useJsonCollection("purchaseReturns"),[saleReturns]=useJsonCollection("saleReturns"),[supplierPayments]=useJsonCollection("supplierPayments"),[customerPayments]=useJsonCollection("customerPayments"),[cashTransactions]=useJsonCollection("partyCashTransactions"),[expenses]=useJsonCollection("expenses"),[products]=useJsonCollection("products");
  const [reportType,setReportType]=useState("purchases"),[basis,setBasis]=useState("supplier"),[basisValue,setBasisValue]=useState(""),[preset,setPreset]=useState("all"),[from,setFrom]=useState(today()),[to,setTo]=useState(today()),[measure,setMeasure]=useState("both"),[trade,setTrade]=useState("all"),[shown,setShown]=useState(false);
  useEffect(()=>{setBasis((bases[reportType]||[])[0]?.[0]||"party");setBasisValue("");setShown(false)},[reportType]);
  const productMap=useMemo(()=>new Map(products.map(p=>[String(p.id),p])),[products]);
  const allRows=useMemo(()=>{
    const prs=purchases.flatMap(p=>{const items=purchaseItems.filter(i=>String(i.purchaseId)===String(p.id));return(items.length?items:[{}]).map(i=>{const product=productMap.get(String(i.productId))||{};return row("خریداری",p,{id:i.id,product:i.productName||product.productName,company:i.manufacturerName||product.manufacturerName,country:product.countryName||product.madeIn,group:product.groupName||product.group,batch:i.batchNo,quantity:i.receivedQuantity??i.quantity,amount:i.lineTotal??p.totalAmount,cost:n(i.purchasePrice)*n(i.receivedQuantity??i.quantity)})})});
    const srs=sales.flatMap(s=>(s.items?.length?s.items:[{}]).map(i=>{const product=productMap.get(String(i.productId))||{};return row("فروشات",s,{id:i.id,product:i.productName||product.productName,company:product.manufacturerName,country:product.countryName||product.madeIn,group:product.groupName||product.group,batch:i.batchNo,quantity:i.quantity??i.packageQuantity,amount:i.lineTotal??s.totalAmount,cost:n(i.purchasePrice)*n(i.quantity??i.packageQuantity)})}));
    const pr=purchaseReturns.map(x=>row("برگشت خریداری",x)),sr=saleReturns.map(x=>row("برگشت فروش",x)),pay=supplierPayments.map(x=>row("تادیه",x)),rec=customerPayments.map(x=>row("طلب",x)),cash=cashTransactions.map(x=>row(x.type==="payment"?"پرداخت نقدی":"دریافت نقدی",x)),exp=expenses.map(x=>row("مصرف",x));
    if(reportType==="purchases")return prs;if(reportType==="sales")return srs;if(reportType==="purchaseReturns")return pr;if(reportType==="saleReturns")return sr;if(reportType==="payables")return pay;if(reportType==="receivables")return rec;if(reportType==="cashFlow")return[...rec,...pay,...cash];if(reportType==="expenses")return exp;if(reportType==="profit")return srs.map(x=>({...x,source:"مفاد",amount:x.amount-x.cost}));return[...prs,...srs,...pr,...sr,...pay,...rec,...cash,...exp];
  },[reportType,purchases,purchaseItems,sales,purchaseReturns,saleReturns,supplierPayments,customerPayments,cashTransactions,expenses,productMap]);
  const basisKey=(x)=>basis==="supplierProduct"?`${x.supplier} - ${x.product}`:basis==="productSupplier"?`${x.product} - ${x.supplier}`:basis==="customerProduct"?`${x.customer} - ${x.product}`:basis==="productCustomer"?`${x.product} - ${x.customer}`:(x[basis]||(basis==="party"?x.party:""));
  const basisOptions=useMemo(()=>[...new Set(allRows.map(basisKey).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"fa")),[allRows,basis]);
  const rows=useMemo(()=>allRows.filter(x=>(preset==="all"||((!from||x.date>=from)&&(!to||x.date<=to)))&&(!basisValue||basisKey(x)===basisValue)).sort((a,b)=>String(b.date).localeCompare(String(a.date))),[allRows,preset,from,to,basisValue,basis]);
  const totals=useMemo(()=>rows.reduce((a,x)=>{a[x.currency]=(a[x.currency]||0)+x.amount;return a},{}),[rows]);
  const applyPreset=(value)=>{setPreset(value);const now=new Date();let start=new Date(now),end=new Date(now);if(value==="yesterday"){start.setDate(start.getDate()-1);end=new Date(start)}if(value==="week")start=weekStart(now);if(value==="lastWeek"){end=weekStart(now);end.setDate(end.getDate()-1);start=new Date(end);start.setDate(start.getDate()-6)}if(value==="month")start=new Date(now.getFullYear(),now.getMonth(),1);if(value==="lastMonth"){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=new Date(now.getFullYear(),now.getMonth(),0)}if(!["all","custom"].includes(value)){setFrom(iso(start));setTo(iso(end))}setShown(false)};
  const exportCsv=()=>{const lines=[["Date","Reference","Type","Party","Product","Quantity","Amount","Currency"],...rows.map(x=>[x.date,x.reference,x.source,x.party,x.product,x.quantity,x.amount,x.currency])];const blob=new Blob(["\ufeff"+lines.map(line=>line.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`report-${reportType}-${today()}.csv`;link.click();URL.revokeObjectURL(link.href)};
  const saveSettings=()=>localStorage.setItem("reports-builder-settings",JSON.stringify({reportType,basis,basisValue,preset,from,to,measure,trade}));
  return <div className="reports-page" dir="rtl">
    <section className="report-builder no-print"><header><div><FileBarChart size={23}/><h1>گزارشات</h1></div><button className="exchange-button" onClick={()=>navigate("/settings")}><Settings2 size={16}/> نرخ تبادله</button></header>
      <div className="report-period"><div className="period-unit"><label><input type="radio" name="unit" defaultChecked/>روز</label><label><input type="radio" name="unit"/>ماه</label><label><input type="radio" name="unit"/>سال</label></div>
        <div className="date-grid"><span>میلادی</span><label>از<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPreset("custom")}}/></label><label>الی<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPreset("custom")}}/></label><span>شمسی</span><label>از<ShamsiDateInput value={from} onChange={e=>{setFrom(e.target.value);setPreset("custom")}}/></label><label>الی<ShamsiDateInput value={to} onChange={e=>{setTo(e.target.value);setPreset("custom")}}/></label></div>
        <div className="preset-row">{[["all","همه"],["today","امروز"],["yesterday","دیروز"],["week","هفته جاری"],["lastWeek","هفته گذشته"],["month","ماه جاری"],["lastMonth","ماه گذشته"],["custom","سفارشی"]].map(([k,l])=><button key={k} className={preset===k?"active":""} onClick={()=>applyPreset(k)}>{l}</button>)}</div></div>
      <div className="report-options"><div className="radio-row"><span>نوع فروش:</span>{[["all","همه"],["wholesale","عمده"],["retail","پرچون"]].map(([k,l])=><label key={k}><input type="radio" name="trade" checked={trade===k} onChange={()=>setTrade(k)}/>{l}</label>)}</div>
        <label>راپور<select value={reportType} onChange={e=>setReportType(e.target.value)}>{reportTypes.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
        <label>به اساس<select value={basis} onChange={e=>{setBasis(e.target.value);setBasisValue("")}}>{(bases[reportType]||[]).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
        <label>انتخاب<div className="search-select"><Search size={15}/><select value={basisValue} onChange={e=>setBasisValue(e.target.value)}><option value="">همه</option>{basisOptions.map(v=><option key={v}>{v}</option>)}</select></div></label>
        <div className="radio-row"><span>نمایش:</span>{[["amount","مبلغ"],["quantity","تعداد"],["both","هر دو"]].map(([k,l])=><label key={k}><input type="radio" name="measure" checked={measure===k} onChange={()=>setMeasure(k)}/>{l}</label>)}</div>
        <div className="report-actions"><button onClick={()=>setShown(true)}><FileBarChart size={17}/> نمایش راپور</button><button className="secondary" onClick={saveSettings}><Save size={16}/> ذخیره تنظیمات</button><span>تعداد راپور: <b>{rows.length}</b></span></div></div>
    </section>
    {shown&&<section className="report-sheet"><div className="report-sheet-tools no-print"><button onClick={()=>window.print()}><Printer size={16}/> چاپ</button><button onClick={exportCsv}><Download size={16}/> CSV</button></div><header><div className="report-brand">APG</div><div><h2>{reportTypes.find(([k])=>k===reportType)?.[1]}</h2><p>{preset==="all"?"تمام دوره‌ها":`${formatAfghanDate(from)} تا ${formatAfghanDate(to)}`} · {basisValue||"همه"}</p></div><div className="report-number">تعداد: {rows.length}</div></header>
      <div className="report-table-wrap"><table><thead><tr><th>#</th><th>تاریخ</th><th>مرجع</th><th>نوع</th><th>شخص / حساب</th><th>محصول</th>{measure!=="amount"&&<th>تعداد</th>}{measure!=="quantity"&&<><th>مبلغ</th><th>واحد پول</th></>}</tr></thead><tbody>{rows.length?rows.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{formatAfghanDate(x.date)||x.date||"-"}</td><td>{x.reference}</td><td>{x.source}</td><td>{x.party}</td><td>{x.product||"-"}</td>{measure!=="amount"&&<td>{money(x.quantity)}</td>}{measure!=="quantity"&&<><td>{money(x.amount)}</td><td>{x.currency}</td></>}</tr>):<tr><td colSpan="9" className="empty-report">برای این فیلتر ریکاردی یافت نشد.</td></tr>}</tbody></table></div>
      {measure!=="quantity"&&<footer>{Object.entries(totals).map(([currency,value])=><div key={currency}><span>مجموع {currency}</span><strong>{money(value)} {currency}</strong></div>)}</footer>}</section>}
  </div>;
}
